name: ae-project-js CI

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Node
      run: npm run mocha -- test-expensive/node.js
    - name: Contracts
      run: npm run mocha -- test-expensive/contracts.js
    - name: Compatibility tests
      run: npm run mocha -- test-expensive/compatibility-tests.js
    - name: Other tests
      run: npm run aetest